#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Sun Mar 26 21:48:38 CST 2017
# Module: ansible
# Submodule: 
# Command: ping
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
#source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function run() {
  log_debug "cmd_line: ${CMD_LINE}"
  ansible_target_hosts=${arg3}
  ansible_module=${arg2}
  log_debug "${ansible_module} ${ansible_target_hosts}"
  args="${CMD_LINE/hi ansible ${ansible_module} ${ansible_target_hosts}/}"
  args="${args/hi_debug/}"
  args=$(echo ${args} | xargs)

  if [ "${args}" != "" ]; then
    cli="ansible ${hosts_conf} ${ansible_target_hosts} -m ${ansible_module} -a "'"'"${args}"'"'" "

    if [ $(echo "${args}" | grep "rm -" | wc -l) != 0 ]; then
      log_info "${cli}"
      if ! prompt_yesorno "Do you wish to execute above command? [yes/no]"; then
        log_info "aborted"
        exit  
      fi
    fi   

    ansible ${hosts_conf} ${ansible_target_hosts} -m ${ansible_module} -a "${args}" 
  else
    cli="ansible ${hosts_conf} ${ansible_target_hosts} -m ${ansible_module} "
    ansible ${hosts_conf} ${ansible_target_hosts} -m ${ansible_module}
  fi

  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
